export const ALUNOS = [
  { id: 1, nome: 'Ana Souza', idade: 20, curso: 'Lógica de Programação' },
  { id: 2, nome: 'Carlos Oliveira', idade: 21, curso: 'Banco de Dados I' },
  { id: 3, nome: 'Beatriz Lima', idade: 19, curso: 'Engenharia de Software' },
  { id: 4, nome: 'Diego Martins', idade: 22, curso: 'Estrutura de Dados' },
  { id: 5, nome: 'Fernanda Silva', idade: 20, curso: 'Programação Web' },
  { id: 6, nome: 'Lucas Almeida', idade: 23, curso: 'Algoritmos e Estruturas de Controle' },
  { id: 7, nome: 'Juliana Rocha', idade: 21, curso: 'Sistemas Operacionais' },
  { id: 8, nome: 'Ricardo Santos', idade: 22, curso: 'Redes de Computadores' },
  { id: 9, nome: 'Mariana Costa', idade: 19, curso: 'Programação Orientada a Objetos' },
  { id: 10, nome: 'João Victor', idade: 24, curso: 'Segurança da Informação' },

  { id: 11, nome: 'Tatiane Mendes', idade: 23, curso: 'Lógica de Programação' },
  { id: 12, nome: 'Gabriel Fernandes', idade: 20, curso: 'Banco de Dados I' },
  { id: 13, nome: 'Larissa Pereira', idade: 22, curso: 'Engenharia de Software' },
  { id: 14, nome: 'Roberto Lima', idade: 25, curso: 'Estrutura de Dados' },
  { id: 15, nome: 'Bruna Ribeiro', idade: 21, curso: 'Programação Web' },
  { id: 16, nome: 'Felipe Azevedo', idade: 24, curso: 'Algoritmos e Estruturas de Controle' },
  { id: 17, nome: 'Patrícia Gomes', idade: 22, curso: 'Sistemas Operacionais' },
  { id: 18, nome: 'Renato Lopes', idade: 20, curso: 'Redes de Computadores' },
  { id: 19, nome: 'Isabela Fernandes', idade: 19, curso: 'Programação Orientada a Objetos' },
  { id: 20, nome: 'Thiago Nunes', idade: 23, curso: 'Segurança da Informação' },

  { id: 21, nome: 'Matheus Teixeira', idade: 20, curso: 'Lógica de Programação' },
  { id: 22, nome: 'Eduarda Neves', idade: 21, curso: 'Banco de Dados I' },
  { id: 23, nome: 'Caio Barbosa', idade: 22, curso: 'Engenharia de Software' },
  { id: 24, nome: 'Isadora Lima', idade: 19, curso: 'Estrutura de Dados' },
  { id: 25, nome: 'Murilo Torres', idade: 23, curso: 'Programação Web' },
  { id: 26, nome: 'Raquel Silva', idade: 20, curso: 'Algoritmos e Estruturas de Controle' },
  { id: 27, nome: 'Henrique Souza', idade: 21, curso: 'Sistemas Operacionais' },
  { id: 28, nome: 'Vitória Cardoso', idade: 22, curso: 'Redes de Computadores' },
  { id: 29, nome: 'André Gonçalves', idade: 24, curso: 'Programação Orientada a Objetos' },
  { id: 30, nome: 'Letícia Santos', idade: 20, curso: 'Segurança da Informação' },

  { id: 31, nome: 'Bruno Ferreira', idade: 23, curso: 'Lógica de Programação' },
  { id: 32, nome: 'Camila Faria', idade: 19, curso: 'Banco de Dados I' },
  { id: 33, nome: 'Vinícius Mendes', idade: 21, curso: 'Engenharia de Software' },
  { id: 34, nome: 'Amanda Rocha', idade: 22, curso: 'Estrutura de Dados' },
  { id: 35, nome: 'Rafael Costa', idade: 20, curso: 'Programação Web' },
  { id: 36, nome: 'Jéssica Ribeiro', idade: 24, curso: 'Algoritmos e Estruturas de Controle' },
  { id: 37, nome: 'Danilo Pires', idade: 22, curso: 'Sistemas Operacionais' },
  { id: 38, nome: 'Natália Lopes', idade: 21, curso: 'Redes de Computadores' },
  { id: 39, nome: 'João Guilherme', idade: 20, curso: 'Programação Orientada a Objetos' },
  { id: 40, nome: 'Bruna Almeida', idade: 19, curso: 'Segurança da Informação' },

  { id: 41, nome: 'Felipe Carvalho', idade: 23, curso: 'Lógica de Programação' },
  { id: 42, nome: 'Sofia Martins', idade: 20, curso: 'Banco de Dados I' },
  { id: 43, nome: 'Leonardo Castro', idade: 21, curso: 'Engenharia de Software' },
  { id: 44, nome: 'Lívia Gomes', idade: 19, curso: 'Estrutura de Dados' },
  { id: 45, nome: 'Igor Tavares', idade: 22, curso: 'Programação Web' },
  { id: 46, nome: 'Yasmin Moura', idade: 20, curso: 'Algoritmos e Estruturas de Controle' },
  { id: 47, nome: 'Pedro Henrique', idade: 21, curso: 'Sistemas Operacionais' },
  { id: 48, nome: 'Milena Andrade', idade: 22, curso: 'Redes de Computadores' },
  { id: 49, nome: 'Caio Batista', idade: 20, curso: 'Programação Orientada a Objetos' },
  { id: 50, nome: 'Luana Freitas', idade: 19, curso: 'Segurança da Informação' }
];
